### ISSUE TITLE
"--hosting-bundle" isn't uninstalling the runtimes, only the Hosting Bundle

### ISSUE THREAD

**Issue by RomBrz** [dotnet/cli-lab#149]
I tested the last version in my lab, i've installed this:
.NET Core SDKs:
.NET Core Runtimes:
  3.1.3   x86
  3.1.3   x64
  2.1.17  x86
  2.1.17  x64
  2.1.16  x86
  2.1.16  x64
ASP.NET Core Runtimes:
.NET Core Runtime & Hosting Bundles:
  3.1.3
  3.1.2
  2.1.17
  2.1.16

Running this:
dotnet-core-uninstall remove --hosting-bundle --all-lower-patches
Give me this:
.NET Core SDKs:
.NET Core Runtimes:
  3.1.3   x86
  3.1.3   x64
  2.1.17  x86
  2.1.17  x64
  2.1.16  x86
  2.1.16  x64
ASP.NET Core Runtimes:
.NET Core Runtime & Hosting Bundles:
  3.1.3
  2.1.17

After that, i ran this:
dotnet-core-uninstall remove --runtime --all-lower-patches
Than i have this:
.NET Core SDKs:
.NET Core Runtimes:
  3.1.3   x86
  3.1.3   x64
  2.1.17  x86
  2.1.17  x64
ASP.NET Core Runtimes:
.NET Core Runtime & Hosting Bundles:
  3.1.3
  2.1.17

1) Doesn't "--hosting-bundle" should uninstall both runtime and hosting bundle?
2) If not, i would like to suggest that i could run, for example "dotnet-core-uninstall remove --all-lower-patches" (or remove --all --all-lower-patches) and the uninstaller clean everything (Runtimes, Hosting Bundles, SDKs).

**Comment by sfoslund** [comment]
Thanks for filing an issue. This is by design, the `--hosting-bundle` option only uninstalls hosting bundles, not runtimes. 

As for running uninstall without specifying a bundle type, we'd like to err on the side of requiring more specificity from the user, as this tool can be destructive. We don't want to create a situation in which the user uninstalls more than they intended so we're going to continue to require the user to specify the bundle type.

**Comment by RomBrz** [comment]
@sfoslund thanks for the answer. 
I opened the issue as the documentation says that the "--hosting-bundle" removes .NET Core runtime and hosting bundles.
https://docs.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=windows
So in this case the command is not running as expected.

If the documentation is incorrect, so why note create a new parameter? I understood that is important to require more specificity from the user, but why i cannot uninstall both?

The fact is that i only deal with the Hosting Bundles (as i work with infra instead of coding) so when i download and install a Hosting Bundle, the runtimes come together, so why when i uninstall a Hosting Bundle i cannot uninstall together the respective runtime with a single command?

Thanks for the attention.

**Comment by sfoslund** [comment]
I see, thanks for pointing out the discrepancy. I've made an issue to track updating the docs: dotnet/docs#18645

There's clearly a trade off here between requiring more of the user (ie two commands instead of one) and getting the specificity to ensure nothing unexpected happens, but for the time being we don't plan on changing this behavior.

**Comment by RomBrz** [comment]
> here's clearly a trade off here between requiring more of the user (ie two commands instead of one) and getting the specificity to ensure nothing unexpected happens

OK, just to make a point, because maybe could be a source of problems to some people, but the hosting bundle default behavior is to uninstall older versions, (If i have the Hosting Bundle 3.1.2 with 3.1.2 runtimes and install the 3.1.3, by default the 3.1.2 runtimes are uninstalled). So doesn't seem to be that dangeours uninstall older versions of the same familly and versions in a way that cannot have at least one extra parameter to "clean older versions".

At least talking about the "Hosting Bundle" behavior... maybe a parameter to use exclusively with --hosting-bundle? (the same way some commands accept a "/force" parameter?)

**Comment by sfoslund** [comment]
Yeah, there are various policies for what is uninstalled in various scenarios (updating to a later patch, updating Visual Studio, etc) for each type of bundle. There's a lot of complexity in this area as these policies differ among bundle types and versions (ex the SDK 3.1, SDK 2.1, hosting bundles, runtimes, etc all have different policies that will continue to evolve with new versions). We don't want to tie this tool to those policies because, for one thing, it would dramatically increase the complexity of the tool and, for another, it would continue to enforce policies that potentially could have been shortsighted or problematic. All in all, I think requiring the user to have to use an extra command here is worth it to keep the tool as simple as possible and easy to reason about.
