### ISSUE TITLE
How to uninstall the preview version SDKs ？

### ISSUE THREAD

**Issue by cnbohu** [dotnet/cli-lab#160]
1.0.0-preview1-002702 [C:\Program Files\dotnet\sdk]
1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
1.0.0-preview2-003156 [C:\Program Files\dotnet\sdk]

**Comment by sfoslund** [comment]
Are these previews not coming up when you run `dotnet-core-uninstall list`?

**Comment by DanielMeixner** [comment]
I have a similar issue, in my case with 5.0-preview. 


**dotnet --list-sdks**
__2.1.202 [C:\Program Files\dotnet\sdk]
2.1.508 [C:\Program Files\dotnet\sdk]
2.1.509 [C:\Program Files\dotnet\sdk]
2.1.511 [C:\Program Files\dotnet\sdk]
2.1.512 [C:\Program Files\dotnet\sdk]
2.1.513 [C:\Program Files\dotnet\sdk]
2.1.515 [C:\Program Files\dotnet\sdk]
2.1.517 [C:\Program Files\dotnet\sdk]
2.1.518 [C:\Program Files\dotnet\sdk]
2.1.801 [C:\Program Files\dotnet\sdk]
3.1.402 [C:\Program Files\dotnet\sdk]
3.1.403 [C:\Program Files\dotnet\sdk]_
5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]_

**dotnet-core-uninstall list**

__This tool can not uninstall versions of the runtime or SDK that are 
    - SDKs installed using Visual Studio 2019 Update 3 or later.
    - SDKs and runtimes installed via zip/scripts.
    - Runtimes installed with SDKs (these should be removed by removing that SDK).
The versions that can be uninstalled with this tool are:_

_.NET Core SDKs:
  3.1.402  x64    [Used by Visual Studio. Specify individually or use --force to remove]
  2.1.801  x64    [Used by Visual Studio 2019. Specify individually or use --force to remove]
  2.1.518  x64    [Used by Visual Studio 2017. Specify individually or use --force to remove]
  2.1.517  x64
  2.1.515  x64
  2.1.513  x64
  2.1.512  x64
  2.1.511  x64
  2.1.509  x64
  2.1.508  x64
  2.1.202  x64    [Used by Visual Studio. Specify individually or use --force to remove]__

I guess it's related to the fact that I installed this via SDK (as mentioned in the output of the uninstall tool). Still it's a little inconvenient to have different ways to uninstall.

**Comment by sfoslund** [comment]
> I guess it's related to the fact that I installed this via SDK

Do you mean installed it via zip? If so, yes, it is expected that it will not show up.

**Comment by MaslovRG** [comment]
I still can't uninstall preview with dotnet-core-uninstall. And what about NET 6?

**Comment by justinmchase** [comment]
```
$ ./dotnet-core-uninstall remove 6.0.100-preview.4.21255.9 --sdk
This tool cannot uninstall .NET Core SDKs with version 6.0.0 or above.
```

How about new previews?

**Comment by sfoslund** [comment]
Yes, that's also expected. Our general rule is that we don't allow uninstalling new major versions until they have been released in GA, so we'll have a new release of this tool in the fall that supports .NET 6.

**Comment by justinmchase** [comment]
I'm not gonna lie, that is a bizarre policy. Uninstalling a preview seems like the most important purpose an uninstaller can possibly have.

**Comment by sfoslund** [comment]
It may sound weird but there are several reasons for this. The main one is that, since this tool is in maintenance and not being actively worked on, we have no testing for the new .NET versions being released. The last release of the tool added support for .NET 5 because at that point it was the latest release and we were able to do comprehensive testing to make sure that the uninstall worked as expected.

However right now, when .NET 6 is still very much in development, we aren't able to test all of the versions that will eventually be release (for example, we can't test .NET 6 RC versions or GA). As a result, if we were to support .NET 6 we would have no way to guarantee that the uninstall would be safe and successful. Theoretically we could release updates occasionally as new versions are released, say release a version that supports uninstalling up to preview 5 right now, but our team does not have the bandwidth so instead we opt for one new release yearly along with GA. 

I hope that makes sense, I see how it can be a confusing policy but it's wrapped up in the team's capacity and testing ability. :)

**Comment by justinmchase** [comment]
I just have an issue with the latest preview (surprise surprise) with no way to uninstall it now. Seems weird to not make it a hard requirement for the team building the installers, especially for the previews.

Thanks for the explanation, I'm not trying to blame you personally it just seems like a backwards priority.

**Comment by sfoslund** [comment]
Understood. Until this tool supports .NET 6 you could try using this uninstall script (as it looks like you're on mac): https://github.com/dotnet/sdk/blob/main/scripts/obtain/uninstall/dotnet-uninstall-pkgs.sh

**Comment by menees** [comment]
> Uninstalling a preview seems like the most important purpose an uninstaller can possibly have.

I agree with @justinmchase 100%!

The Windows x64 uninstaller for SDK 6.0.100-preview.5 deletes some files, but it leaves several folders and files behind. That breaks some dotnet CLI tasks, e.g., "dotnet --info" failing because it can't find dotnet.dll in the leftover 6.0.x folders. I tried dotnet-core-uninstall, but it was unhelpful.

To manually clean this up I had to search "C:\Program Files\dotnet" for every folder containing "preview.5" because there were so many different 6.0.0, 6.0.100, etc. folders with slightly different build or revision numbers. After deleting those folders, now all my dotnet CLI operations are succeeding again. I also used NirSoft's RegScanner to find and delete about 1000 places in the registry that still referred to those 6.0.x folders.

There ought to be a utility for this. ;-)

**Comment by u2m4c6** [comment]
I understand this tool is in maintenance, but it seems odd not to have a tool to uninstall preview versions. Like others have said, of all things an uninstall tool should be able to do, uninstall a preview is it. It is hard to evaluate .NET 6.0 preview 6 for example when preview 5 is still installed. What I have had to do in the past is just nuke my .dotnet folders and reinstall everything from scratch. Silly, but ends up being the least annoying path.

**Comment by khalylk** [comment]
An unfortunate decision which impacts customers, costing time and effort.

**Comment by justinmchase** [comment]
@sfoslund by the way, I ended up recently running the script you shared in https://github.com/dotnet/cli-lab/issues/160#issuecomment-872346700 and it uninstalled more than I was expecting but it did work. I was able to just re-install the SDK version I wanted and all was well again. Thanks!

**Comment by Lemraj** [comment]
Check the .NET Uninstall Tool:
https://docs.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool

**Comment by suwet** [comment]
try to you download setup last version , install process ,select uninstall ,not repair

**Comment by justinmchase** [comment]
@Lemraj Unfortunately the uninstall tool only installs official version. Pre-release versions cannot be uninstalled with that tool, which is sad because pre-release versions are the ones you typically want to uninstall the most.

**Comment by resting** [comment]
Here for the same reasons
Am I stuck with the `rc` and `preview` taking up space now that .net 7 is officially released?
```
.NET Core SDKs:
  7.0.100-rc.2.22477.23      (x64)  [Cannot uninstall version 7.0.0 and above]
  7.0.100-preview.7.22377.5  (x64)  [Cannot uninstall version 7.0.0 and above]
  7.0.100                    (x64)  [Cannot uninstall version 7.0.0 and above]
  6.0.400                    (x64)  [Used by Visual Studio for Mac. Specify individually or use —-force to remove]
```

**Comment by justinmchase** [comment]
Please see [this comment](https://github.com/dotnet/cli-lab/issues/160#issuecomment-872346700) for a solution. It did work for .net6 and will probably work for 7 also but maybe look in the script and double check. Its _not_ an officially supported solution so use at your own risk.
