### ISSUE TITLE
VS 2022 Release Candidate Uninstall - ERROR The specified version is not valid

### ISSUE THREAD

**Issue by tgourley** [dotnet/cli-lab#204]
I am getting the following error when trying to list .NET versions to try and uninstall:
`The specified version is not valid: "".`

I see another issue #200 being discussed, but I am wondering if mine is related to the previews and release candidates of .NET 6.

I have had issues getting VS 2022 working and ultimately decided to uninstall it.  .NET 6 installs with VS 2022 (not separate) but the uninstall seems incomplete (as seen in the screenshot below.)

![image](https://user-images.githubusercontent.com/495655/135156702-7bf2744a-d15a-4aca-a55c-ea32295dc90a.png)

I have a couple of preview copies of .NET 6 as well as one instance of the release candidate.  These should have been deleted with VS 2022.  This lead me to the dotnet-core-uninstall utility in hopes of cleaning those versions out.

**Comment by sfoslund** [comment]
Based on the screenshots it looks like you're not providing the required options in your command. If you're looking to uninstall a runtime of that version, you'll need to include the `--runtime` flag (you can run dry-run --help for more info). 

That being said, I'm not sure that the uninstall tool is the right thing here. As it says in the help output in the screenshot, this tool cannot uninstall any bundles that were installed via Visual Studio. You can run the list command to see what bundles are available to be uninstalled.

**Comment by tgourley** [comment]
Well, I am grasping at straws to try and get these preview versions uninstalled.  But I get the same error with just the list command.
![image](https://user-images.githubusercontent.com/495655/135159418-5dc00b48-2e1e-42fc-840a-a2a8f559ed92.png)

**Comment by sfoslund** [comment]
Do they come up in add/remove programs?

**Comment by tgourley** [comment]
Only up to .NET 5 (which has two, one SDK and one "from Visual Studio")
![image](https://user-images.githubusercontent.com/495655/135162500-6ca899a0-68aa-49c3-899c-0b8d97bb80c8.png)

**Comment by sfoslund** [comment]
Okay, any .NET installations that don't show up in the add/removes programs were likely installed via zip files which don't write to the registry. As a result, the uninstall tool and add/remove programs both won't be able to uninstall them (since they're just files laid down on disk). There's not a great answer for how to uninstall these bundles, as it's generally not recommended that you install via zips to program files.

**Comment by tgourley** [comment]
Well I cannot account for other processes, but I can assure that I haven't installed via ZIP files (sounds crazy to me.) I can only think of three ways they get installed: windows updates, visual studio install/updates, or I sometimes have to use the .NET SDK MSI installer through Microsoft. But, if I can't get this uninstalled CLI to work, I will move on I guess.

**Comment by sfoslund** [comment]
I'm not sure how those installations could have shown up like that then, since windows updates, Visual Studio, and standalone SDK MSIs all write to the registry and as a result would show up in add/remove programs. If you don't have any zip installs, then something very weird is going on with the machine. Sorry I can't be more helpful

**Comment by tgourley** [comment]
I ended up just going through the `C:\Program Files\dotnet` folder and deleting any remnants of .NET 6 previews/RC.  I will still getting the same error as before when trying to run the list command, but at this point I am going to try something else.  Thanks!
