### ISSUE TITLE
List of UI issues

### ISSUE THREAD

**Issue by yuchong-pan** [dotnet/cli-lab#6]
1. Shall we list and uninstall x64 SDKs only, or both x64 and x86?
2. What is the form of the output of `dotnet uninstall list`?
3. `dotnet uninstall uninstall [OPTION]`, or `dotnet uninstall [OPTION]`, or another verb for subsubcommand?
4. `uninstall --all` cannot really uninstall, or there is nothing to run on.
5. "Not supported" for the Linux version?

**Comment by KathleenDollard** [comment]
1. I think we need to consider both. That might require more syntax. 
2. Suggest something that makes sense please. And we can have variations because we have different verbosity levels. 
3. dotnet uninstall [OPTION]
4. Rats. Suggest we uninstall all but current and then print a warning. For now use this text:
"All .NET Core SDKs have been removed except {version} which was running the uninstall. Please uninstall this in Windows Add/Remove programs"
5. "Not supported" anywhere we can't install. Definitely Linux, Mac if we aren't doing it yet.
