### ISSUE TITLE
dotnet-core-uninstall mustn't mess up my VS

### ISSUE THREAD

**Issue by shanselman** [dotnet/cli-lab#88]
dotnet-core-uninstall mustn't mess up my VS ever. Meaning, no matter what I do, it shouldn't uninstall an SDK that is needed for VS 2019 to be successful. Yes, VS2019 can be repaired (is that a good scenario? torch *.* and then require repair and kicking it off? A problem if you have x SDKs and y VS2019 installs).

Another idea would be a JSON file of stored VS+SDK versions and detect VS version and mark the SDK it needs? I'd propose you need to NOT break any VS that depended on the VS2019 wave.

**Comment by KathleenDollard** [comment]
I suggest that we do an initial release, marked as preview if possible, without this change. Can we do this via releases on this repo?

This protection will be valuable as we roll this out to the Visual Studio customers that are most affected (because they are prompted to update) by the copies of the SDK and runtime we left behind. Let's delay widespread release until we have this, or have broader buy-in on the risk. 

Jacques may have some stuff that will help.

**Comment by sfoslund** [comment]
Addressed in PR #95
